In [2]:


import pandas as pd


df = pd.read_csv("captions.csv")

df.head()

,image_name,comment_number,comment;
0,1000092795.jpg,0,Two young guys with shaggy hair look at their...
1,1000092795.jpg,1,Two young White males are outside near many ...
2,1000092795.jpg,2,Two men in green shirts are standing in a yar...
3,1000092795.jpg,3,A man in a blue shirt standing in a garden .;
4,1000092795.jpg,4,Two friends enjoy time spent together .;

In [4]:
# Remove trailing semicolons from all column values
df = df.applymap(lambda x: str(x).rstrip(';') if isinstance(x, str) else x)
df.head(20)

C:\Users\sara0\AppData\Local\Temp\ipykernel_4340\1477385087.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: str(x).rstrip(';') if isinstance(x, str) else x)

,image_name,comment_number,comment;
0,1000092795.jpg,0,Two young guys with shaggy hair look at their...
1,1000092795.jpg,1,Two young White males are outside near many ...
2,1000092795.jpg,2,Two men in green shirts are standing in a yard .
3,1000092795.jpg,3,A man in a blue shirt standing in a garden .
4,1000092795.jpg,4,Two friends enjoy time spent together .
5,10002456.jpg,0,Several men in hard hats are operating a gian...
6,10002456.jpg,1,Workers look down from up above on a piece of...
7,10002456.jpg,2,Two men working on a machine wearing hard hats .
8,10002456.jpg,3,Four men on top of a tall structure .
9,10002456.jpg,4,Three men on a large rig .
10,1000268201.jpg,0,A child in a pink dress is climbing up a set ...
11,1000268201.jpg,1,A little girl in a pink dress going into a wo...
12,1000268201.jpg,2,A little girl climbing the stairs to her play...
13,1000268201.jpg,3,A little girl climbing into a wooden playhouse
14,1000268201.jpg,4,A girl going into a wooden building .
15,1000344755.jpg,0,Someone in a blue shirt and hat is standing o...
16,1000344755.jpg,1,A man in a blue shirt is standing on a ladder...
17,1000344755.jpg,2,A man on a ladder cleans the window of a tall...
18,1000344755.jpg,3,man in blue shirt and jeans on ladder cleanin...
19,1000344755.jpg,4,a man on a ladder cleans a window

In [6]:
df['image_name'] = df['image_name'].str.strip()
df.head()

,image_name,comment_number,comment;
0,1000092795.jpg,0,Two young guys with shaggy hair look at their...
1,1000092795.jpg,1,Two young White males are outside near many ...
2,1000092795.jpg,2,Two men in green shirts are standing in a yard .
3,1000092795.jpg,3,A man in a blue shirt standing in a garden .
4,1000092795.jpg,4,Two friends enjoy time spent together .

In [8]:
print(df.columns)

Index(['image_name', ' comment_number', ' comment;'], dtype='object')

In [10]:
import nltk
import os
# Path to your virtual environment's nltk_data directory
nltk_data_path = os.path.join('venv', 'nltk_data')

# Ensure the directory exists
os.makedirs(nltk_data_path, exist_ok=True)

# Add this path to NLTK's data paths
nltk.data.path.append(nltk_data_path)

# Download punkt
nltk.download('punkt', download_dir=nltk_data_path)

[nltk_data] Downloading package punkt to venv\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [12]:
def preprocess_caption(caption):
    # Lowercase
    caption = caption.lower()
    # Tokenize
    tokens = nltk.word_tokenize(caption)
    # Join tokens
    return " ".join(tokens)

# Apply preprocessing
df['cleaned_caption'] = df[' comment;'].apply(preprocess_caption)
df['cleaned_caption'].head()

LookupError:
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - 'C:\\Users\\sara0/nltk_data'
    - 'c:\\Users\\sara0\\Desktop\\uni\\THIRD YEAR\\VISION AND LEARNING\\Cloned repository Challenge 3\\Image-Captioning\\venv\\nltk_data'
    - 'c:\\Users\\sara0\\Desktop\\uni\\THIRD YEAR\\VISION AND LEARNING\\Cloned repository Challenge 3\\Image-Captioning\\venv\\share\\nltk_data'
    - 'c:\\Users\\sara0\\Desktop\\uni\\THIRD YEAR\\VISION AND LEARNING\\Cloned repository Challenge 3\\Image-Captioning\\venv\\lib\\nltk_data'
    - 'C:\\Users\\sara0\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - 'venv\\nltk_data'
**********************************************************************